apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted=psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requireDropCapabilites:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroup:
    rule: MustRunAs
    range:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535