name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.3
        
        - name: Build
          run: |
            cd cmd
            go build -o ../main
            cd ..
            
        - name: Build Docker image
          run: docker build -t ${{secrets.DOCKER_USERNAME}}/golang-app:latest .

        - name: Log in to Docker Hub
          run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
        
        - name: Push Docker image
          run: docker push ${{secrets.DOCKER_USERNAME}}/golang-app:latest
    
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        # - name: Setup kubectl
        #   uses: azure/setup-kubectl@v1
        #   with:
        #     version: 'latest'
        
        - name: Set up minikube
          uses: engineerd/setup-minikube@v1
          with:
            minikube-version: latest
            kubectl-version: latest
            driver: docker
            
        - name: Configure kubectl
          run: |
            minikube kubectl -- get pods -n kube-system  # Test kubectl setup
            minikube kubectl -- apply -f argocd/application.yaml

        - name: Apply ArgoCD application
          run: |
            kubectl config view
            kubectl config current-context
            kubectl get pods -n argocd
            kubectl apply -f argocd/application.yaml --validate=false
        #   env:
        #     KUBECONFIG: ${{secrets.KUBECONFIG}}
            

        - name: Deploy to k8s
        #   env:
        #      KUBECONFIG: ${{secrets.KUBECONFIG}}
          run: |
            kubectl apply -f k8s/helm/deployment.yaml